### ISSUE TITLE
Lost result and exceptions with cider

### ISSUE THREAD

**Issue by danskarda** [cemerick/piggieback#31]
Recently Emacs Cider changed behavior of eval expression. It internally
uses nrepl load-file instead of eval. This works fine for Clojure, but
it breaks ClojureScript evaluation. User cannot see result of his
expression and even exceptions are lost.

The reason for the bug is difference between CLJ and CLJS load function.
While CLJ load returns last expression, ClojureScript returns nil. 

It would be dangerous to change CLJS load function itself. CLJS does not
have variables and last file expression (def x (complex-value)) would
result in performance penalty due to printing of complex value.

I propose workaround to modify piggieback to return value of last expression in load-file. This would fix the issue and give us more time solve in better way: find why cider needs load-file instead of eval and update eval to meet cider needs.

For more details see  clojure-emacs/cider#830

**Comment by cemerick** [comment]
The work on the `new-cljs-repl` branch, currently available in `0.2.0-SNAPSHOT`, is effectively a rewrite due to the new ClojureScript REPL API, etc. Closing all issues filed against `0.1.x`; most (or all) of them should be resolved and/or irrelevant.
