### ISSUE TITLE
Add support for :merge-opts in REPL -setup return value

### ISSUE THREAD

**Issue by mfikes** [cemerick/piggieback#43]
ClojureScript master [has been updated](https://github.com/clojure/clojurescript/commit/62e4b349f966e6895dae5e0073b5df894a492c0d) to allow REPLs to further configure compilation as a result of executing `-setup`. This is done by looking up a special `:merge-opts` key in the return value of `-setup`, and merging those options back into the original options.

This enhancement request is for the same support in Piggieback.

**Comment by mfikes** [comment]
This request was borne out of omcljs/ambly#28

The change in the PR is small and I've verified that it does what is needed for Ambly. But, it is difficult for me to see whether there might be any bad consequences.

**Comment by cemerick** [comment]
Available now in 0.1.6-SNAPSHOT. Not sure when I'll cut a release next, but that should hold you over until I do. :-)

**Comment by mfikes** [comment]
Perfect! I've tested against the 0.1.6-SNAPSHOT that resolved to `0.1.6-20150220.115516-2` in Clojars and it worked.

A SNAPSHOT is more than sufficient for our purposes. No need to cut a release anytime soon for this particular change. Thanks!
