### ISSUE TITLE
cljs-repl needs to check for upstream deps

### ISSUE THREAD

**Issue by swannodette** [cemerick/piggieback#45]
Note this is unnecessary if piggieback was a proper nREPL middleware over CLJS REPLs as then it could stop repeating existing logic.

The options passed to the compiler environment doesn't pass upstream deps preventing proper indexing.
https://github.com/cemerick/piggieback/blob/master/src/cemerick/piggieback.clj#L191

As of this commit https://github.com/cemerick/piggieback/commit/a9b88c33e78aa5de80c1d5952a5d658dc062f046 REPLs can solve this themselves, but that's undesirable for obvious reasons.

**Comment by cemerick** [comment]
Fix available now in `0.1.6-SNAPSHOT`.
