### ISSUE TITLE
run-cljs-repl does not use options argument [0.2.0]

### ISSUE THREAD

**Issue by danskarda** [cemerick/piggieback#56]
It seems strange to me that new piggieback/cljs-repl stores options and passes it to run-cljs-repl, but run-cljs-repl actually does not use this argument. Should there be `(repl repl-env (merge {.....} options))`?

https://github.com/cemerick/piggieback/blob/new-cljs-repl/src/cemerick/piggieback.clj#L122

**Comment by cemerick** [comment]
Thanks, good catch! Was a casualty of earlier refactorings. Fixed on the branch, and new `0.2.0-SNAPSHOT` deployed.
