### ISSUE TITLE
Unable to complete from namespace alias

### ISSUE THREAD

**Issue by 4xrsJCr9** [cemerick/piggieback#63]
After evaluating `(require '[clojure.string :as s])` in the repl, cider is unable to complete after `s/`. It can however complete correctly after `clojure.string/`.

- cider 0.9.0-SNAPSHOT
- nrepl 0.2.10
- piggieback 0.2.1
- clojurescript 0-0.3269

Not sure if this is a piggieback issue or a cider issue.

**Comment by cemerick** [comment]
Piggieback has no involvement in code completion. Look to cider and its components.

**Comment by 4xrsJCr9** [comment]
Will do.

I had noticed that this only occurs when piggieback is active, so it seemed as good a place as any to start. I'll look into the issue a bit more and see if I can find the root cause.

**Comment by 4xrsJCr9** [comment]
In case anyone else ends up here with the same issue, please look at https://github.com/gtrak/cljs-tooling/pull/19.
