### ISSUE TITLE
Problem with node repl in 0.0-3269

### ISSUE THREAD

**Issue by rbuchmann** [cemerick/piggieback#65]
I am using piggieback to start a node repl from emacs/cider using (cemerick.piggieback/cljs-repl (cljs.repl.node/repl-env)). The repl starts ok, and I can eval forms, however when I C-c C-k to load the buffer, it just says "Loading foo.cljs..." forever. I can run code from the ns, but none of the required or macro-required namespaces seem to be present.

**Comment by cemerick** [comment]
Sounds like you're using `0.2.0`? The latest rev is `0.2.1`. The README didn't reflect this until a few minutes ago, if that's what led you astray.

**Comment by rbuchmann** [comment]
That fixed it, thanks. Sorry for not checking before.
