### ISSUE TITLE
It is possible to just eval in CLJS and not create a new REPL for each evaluation

### ISSUE THREAD

**Issue by bhauman** [cemerick/piggieback#79]
This code details how its possible to just have an eval and not have to do a full cljs-repl boot for each evaluation.

The functions highlighted below only need to be evaluated with cljs.env/*compliler* bound.

https://github.com/bhauman/rebel-readline/blob/master/rebel-readline-cljs/src/rebel_readline/cljs/service/local.clj#L57-L79

This will speed up the evaluation significantly and as a bonus simplify things so that we can evaluate all the sent forms and provide interrupt to get the prompt back.

This is a very straightforward fix. 
@cemerick ^

**Comment by bbatsov** [comment]
The link you've posted seems to be broken.

**Comment by bhauman** [comment]
I fixed the link.

**Comment by cemerick** [comment]
Hi Bruce!

I'm sorry for the radio silence. I know you've been eager to get this (finally) folded in.

I need to just admit that I'm not likely to return to this, nevermind continuing proper maintenance and such. So, I want to get out of your way.

Can I give you commit, and then you can do whatever you think is right? Presumably we can also get you appropriate privs on clojars.

You can catch me on irc most of the time, where we can work out any details, etc.

**Comment by bhauman** [comment]
Sounds great. :)
